Failure # 1 (occurred at 2021-05-22_23-06-39)
Traceback (most recent call last):
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=21668, ip=172.17.0.9)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 121, in __init__
    Trainer.__init__(self, config, env, logger_creator)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 516, in __init__
    super().__init__(config, logger_creator)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/tune/trainable.py", line 98, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 707, in setup
    self._init(self.config, self.env_creator)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 153, in _init
    num_workers=self.config["num_workers"])
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 789, in _make_workers
    logdir=self.logdir)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/evaluation/worker_set.py", line 81, in __init__
    lambda p, pid: (pid, p.observation_space, p.action_space)))
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=21672, ip=172.17.0.9)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 449, in ray._raylet.execute_task.function_executor
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/_private/function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 383, in __init__
    self.env = _validate_env(env_creator(env_context))
  File "/root/anaconda3/envs/solar_panels_rl/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 1339, in <lambda>
    register_env(name, lambda config: env_object(config))
  File "/root/Hanhwa-AlphaSolar/alphasolar/env.py", line 523, in __init__
    super(AlphaSolarEnv, self).__init__(**env_config)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

